package com.app.srivyaradio.utils

object Constants {
    const val LOCATION_API_URL = "http://ip-api.com/"
    const val STATIONS_API_URL = "https://srivyaa.github.io/RadioStations/"
    const val COUNTRY_CODE = "countryCode"
    const val LANGUAGE_CODE = "languageCode"
    const val IS_FIRST_START = "isFirstStartup"
    const val MODE = "mode"
    const val LAST_PLAY = "lastPlay"
    const val VERSION = "version"
    const val HAS_PURCHASED = "hasPurchased"
    const val DATABASE = "database"
    const val SHARED_PREF = "radiotimepref"
    const val FAVORITES_ID = "favorites"
    const val DISCOVER_ID = "discover"
    const val COUNTRIES_ID = "countries"
    const val LANGUAGES_ID = "languages"
    const val COUNTRY_PREFIX = "country_"
    const val ROOT_ID = "root"
    const val CHANGE_COUNTRY_KEY = "KEY_CHANGE_COUNTRY"
    const val CHANGE_COUNTRY_COMMAND = "COMMAND_CHANGE_COUNTRY"
    const val CHANGE_LANGUAGE_KEY = "KEY_CHANGE_LANGUAGE"
    const val CHANGE_LANGUAGE_COMMAND = "COMMAND_CHANGE_LANGUAGE"
    const val UPDATE_FAVORITE_COMMAND = "COMMAND_UPDATE_FAVORITE"
    const val TOGGLE_FAVORITE_COMMAND = "COMMAND_TOGGLE_FAVORITE"
    const val TOGGLE_FAVORITE_STATION_ID_KEY = "KEY_TOGGLE_FAVORITE_STATION_ID"
    const val SET_TIMER_KEY = "KEY_SET_TIMER"
    const val SET_TIMER_COMMAND = "COMMAND_SET_TIMER"
    const val PLAY_NEXT_COMMAND = "COMMAND_PLAY_NEXT"
    const val PLAY_PREVIOUS_COMMAND = "COMMAND_PLAY_PREVIOUS"
    const val SET_QUEUE_COMMAND = "COMMAND_SET_QUEUE"
    const val SET_QUEUE_ITEMS_KEY = "KEY_SET_QUEUE_ITEMS"
    const val SET_QUEUE_INDEX_KEY = "KEY_SET_QUEUE_INDEX"
    const val SET_QUEUE_TAG_KEY = "KEY_SET_QUEUE_TAG"
    const val RADIO_LOGO = "https://srivyaa.github.io/ImageHost/ic_radiologo.png"
}