package com.app.srivyaradio.utils

val countryList = listOf(
    // Custom Radio Categories (alphabetically sorted)
    Pair("All_India_Radios 🇮🇳", "INDIA"),
    Pair("Actor_Radios 🎭", "ACTOR"),
    Pair("Ajith_Radios 🎬", "AJITH"),
    Pair("Amma_Radios 👵", "AMMA"),
    Pair("Appa_Radios 👨‍👧‍👦", "APPA"),
    Pair("Arjun_Radios 🦁", "ARJUN"),
    Pair("Captain_Radios 🕶️", "CAPTAIN"),
    Pair("Amman_Radio 🕉️", "AMMAN"),
    Pair("Artist_Radios 🎤", "ARTIST"),
    Pair("Christian_Radios ✝️", "CHRIST"),
    Pair("Community_Radios 🏘️", "COMMUNITY"),
    Pair("Classic_Radios 🎻", "CLASSIC"),
    Pair("Deva_Radios 🎵", "DEVA"),
    Pair("English_Radios 🇬🇧", "ENGLISH"),
    Pair("Ganapathy_Radios 🐘", "GANAPATHY"),
    Pair("Hindu_Radio 🕉️", "HINDU"),
    Pair("Hindi_Radios 🇮🇳", "HINDI"),
    Pair("JR_Radios 🦸", "JR"),
    Pair("Islam_Radios ☪️", "ISLAM"),
    Pair("Kamal_Radios 🎭", "KAMAL"),
    Pair("Kids_Radios 👶", "KIDS"),
    Pair("Kutties_Radios 👶", "KUTTIES"),
    Pair("Local_Radios 📍", "LOCAL"),
    Pair("Local_TV ▶️", "LOCALTV"),
    Pair("MP3 🎵", "MP3"),
    Pair("Music_Radio 🎵", "MUSIC"),
    Pair("Manisharma_Radios 🎶", "MANISHARMA"),
    Pair("Mass_Radios 💥", "MASS"),
    Pair("Mohan_Radios 🎤", "MOHAN"),
    Pair("Perumal_Songs 🕉️", "PERUMAL"),
    Pair("Pongal_Specials 🎉", "PONGAL"),
    Pair("Prasanth_Radios 🎵", "PRASANTH"),
    Pair("Prithishaa_Radios 🌟", "PRITHISHAA"),
    Pair("Rajini_Radios 👑", "RAJINI"),
    Pair("Ramarajan_Radios 🎤", "RAMARAJAN"),
    Pair("SA Rajkumar_Radios 🎭", "SARAJKUMAR"),
    Pair("Sirpy_Radios 🎵", "SIRPY"),
    Pair("SV_Sekar_Dramas 🎭", "SVS"),
    Pair("Tamil_FM_Radios 🇮🇳", "TAMILFM"),
    Pair("Tamil_TV_Channels 📺", "TAMILTV"),
    Pair("Tamil_Talk_Radios 💬", "TAMILTALK"),
    Pair("TMS_Murugan_Songs 🕉️", "TMS"),
    Pair("TR_Hits_Radios 🔥", "TRHITS"),
    Pair("TV_Serials 🎵", "SERIALS"),
    Pair("Unplugged_Radios 🎸", "UNPLUGGED"),
    Pair("Vikram_Radios 🦹", "VIKRAM"),
    Pair("🏹 Mahabharat_Radios", "MAHABHARAT"),
    Pair("▶️ YouTube", "YOUTUBE"),
    
    // Countries
    Pair("🇮🇳 India", "IN"),
    Pair("🇮🇪 Ireland", "IE")
)
