package com.app.srivyaradio.utils

val countryList = listOf(
    // Custom Radio Categories (alphabetically sorted)
    Pair("AJITH HITS 🎬", "AJITHHITS"),
    Pair("All India Radios 🇮🇳", "INDIA"),
    Pair("Amman Radio 🕉️", "AMMAN"),
    Pair("Appa Radios 👨‍👧‍👦", "APPA"),
    Pair("Appa(1) Radios 👨‍👧‍👦", "APPA(1)"),
    Pair("Arjun Radios 🦁", "ARJUN"),
    Pair("ARR Melodies 🎵", "ARRMELODIES"),
    Pair("Artist Radios 🎤", "ARTIST"),
    Pair("Captain Radios 🕶️", "CAPTAIN"),
    Pair("Christian Radios ✝️", "CHRIST"),
    Pair("Classic Radios 🎻", "CLASSIC"),
    Pair("Community Radios 🏘️", "COMMUNITY"),
    Pair("Dance Hits 🎵", "DANCESONGS"),
    Pair("Deva Radios 🎵", "DEVA"),
    Pair("English Radios 🇬🇧", "ENGLISH"),
    Pair("English Rhymes 📚", "ENGRHYMES"),
    Pair("Ganapathy Radios 🐘", "GANAPATHY"),
    Pair("Hindu Radio 🕉️", "HINDU"),
    Pair("Hindi Radios 🇮🇳", "HINDI"),
    Pair("Islam Radios ☪️", "ISLAM"),
    Pair("Jeyam Ravi Hits 🎬", "JEYAM_RAVI_HITS"),
    Pair("Jeyam Ravi Hits(1) 🎬", "JEYAM_RAVI_HITS(1)"),
    Pair("JR Radios 🦸", "JR"),
    Pair("Kamal Radios 🎭", "KAMAL"),
    Pair("Kamal Hits 🎬", "KAMAL_HITS"),
    Pair("Kids Radios 👶", "KIDS"),
    Pair("Kids TV 📺", "KIDS1"),
    Pair("Kids3 📺", "KIDS2"),
    Pair("Kutties Radios 👶", "KUTTIES"),
    Pair("Local Radios 📍", "LOCAL"),
    Pair("Local TV 📺", "LCLTV"),
    Pair("Local TV ▶️", "LOCALTV"),
    Pair("MP3 🎵", "MP3"),
    Pair("MP3 Links 🎵", "MP3_LINKS"),
    Pair("Manisharma Radios 🎶", "MANISHARMA"),
    Pair("Mass Radios 💥", "MASS"),
    Pair("Melodies 🎵", "MELODIES"),
    Pair("Mixed Songs 🎵", "MIXED"),
    Pair("Mohan Radios 🎤", "MOHAN"),
    Pair("Music Radio 🎵", "MUSIC"),
    Pair("Perumal Songs 🕉️", "PERUMAL"),
    Pair("Petta 🎬", "PETTA"),
    Pair("Pongal Specials 🎉", "PONGAL"),
    Pair("Prasanth Radios 🎵", "PRASANTH"),
    Pair("Prithishaa Radios 🌟", "PRITHISHAA"),
    Pair("Rajini Radios 👑", "RAJINI"),
    Pair("Ramarajan Radios 🎤", "RAMARAJAN"),
    Pair("SA Rajkumar Radios 🎭", "SARAJKUMAR"),
    Pair("Samadada 1-13 🎭", "SAMADADA_1"),
    Pair("Samadada 2-13 🎭", "SAMADADA_2"),
    Pair("Samadada 3-13 🎭", "SAMADADA_3"),
    Pair("Samadada 4-13 🎭", "SAMADADA_4"),
    Pair("Samadada 5-13 🎭", "SAMADADA_5"),
    Pair("Samadada 6-13 🎭", "SAMADADA_6"),
    Pair("Samadada 7-13 🎭", "SAMADADA_7"),
    Pair("Samadada 8-13 🎭", "SAMADADA_8"),
    Pair("Samadada 9-13 🎭", "SAMADADA_9"),
    Pair("Samadada 10-13 🎭", "SAMADADA_10"),
    Pair("Samadada 11-13 🎭", "SAMADADA_11"),
    Pair("Samadada 12-13 🎭", "SAMADADA_12"),
    Pair("Samadada 13-13 🎭", "SAMADADA_13"),
    Pair("Sirpy Radios 🎵", "SIRPY"),
    Pair("SV Sekar Dramas 🎭", "SVS"),
    Pair("Tamil FM Radios 🇮🇳", "TAMILFM"),
    Pair("Tamil Musics 🎵", "MP3_LINKS"),
    Pair("Tamil Talk Radios 💬", "TAMILTALK"),
    Pair("Tamil TV Channels 📺", "TAMILTV"),
    Pair("TMS Murugan Songs 🕉️", "TMS"),
    Pair("TR Hits Radios 🔥", "TRHITS"),
    Pair("TV Serials 🎵", "SERIALS"),
    Pair("Unplugged Radios 🎸", "UNPLUGGED"),
    Pair("Vikram Radios 🦹", "VIKRAM"),
    Pair("🏹 Mahabharat Radios", "MAHABHARAT"),
    Pair("▶️ YouTube", "YOUTUBE"),
    
    // MP3 Links (1-124)
    Pair("MP3 Links 1 🎵", "MP3_LINKS_1"),
    Pair("MP3 Links 2 🎵", "MP3_LINKS_2"),
    Pair("MP3 Links 3 🎵", "MP3_LINKS_3"),
    Pair("MP3 Links 4 🎵", "MP3_LINKS_4"),
    Pair("MP3 Links 5 🎵", "MP3_LINKS_5"),
    Pair("MP3 Links 6 🎵", "MP3_LINKS_6"),
    Pair("MP3 Links 7 🎵", "MP3_LINKS_7"),
    Pair("MP3 Links 8 🎵", "MP3_LINKS_8"),
    Pair("MP3 Links 9 🎵", "MP3_LINKS_9"),
    Pair("MP3 Links 10 🎵", "MP3_LINKS_10"),
    Pair("MP3 Links 11 🎵", "MP3_LINKS_11"),
    Pair("MP3 Links 12 🎵", "MP3_LINKS_12"),
    Pair("MP3 Links 13 🎵", "MP3_LINKS_13"),
    Pair("MP3 Links 14 🎵", "MP3_LINKS_14"),
    Pair("MP3 Links 15 🎵", "MP3_LINKS_15"),
    Pair("MP3 Links 16 🎵", "MP3_LINKS_16"),
    Pair("MP3 Links 17 🎵", "MP3_LINKS_17"),
    Pair("MP3 Links 18 🎵", "MP3_LINKS_18"),
    Pair("MP3 Links 19 🎵", "MP3_LINKS_19"),
    Pair("MP3 Links 20 🎵", "MP3_LINKS_20"),
    Pair("MP3 Links 21 🎵", "MP3_LINKS_21"),
    Pair("MP3 Links 22 🎵", "MP3_LINKS_22"),
    Pair("MP3 Links 23 🎵", "MP3_LINKS_23"),
    Pair("MP3 Links 24 🎵", "MP3_LINKS_24"),
    Pair("MP3 Links 25 🎵", "MP3_LINKS_25"),
    Pair("MP3 Links 26 🎵", "MP3_LINKS_26"),
    Pair("MP3 Links 27 🎵", "MP3_LINKS_27"),
    Pair("MP3 Links 28 🎵", "MP3_LINKS_28"),
    Pair("MP3 Links 29 🎵", "MP3_LINKS_29"),
    Pair("MP3 Links 30 🎵", "MP3_LINKS_30"),
    Pair("MP3 Links 31 🎵", "MP3_LINKS_31"),
    Pair("MP3 Links 32 🎵", "MP3_LINKS_32"),
    Pair("MP3 Links 33 🎵", "MP3_LINKS_33"),
    Pair("MP3 Links 34 🎵", "MP3_LINKS_34"),
    Pair("MP3 Links 35 🎵", "MP3_LINKS_35"),
    Pair("MP3 Links 36 🎵", "MP3_LINKS_36"),
    Pair("MP3 Links 37 🎵", "MP3_LINKS_37"),
    Pair("MP3 Links 38 🎵", "MP3_LINKS_38"),
    Pair("MP3 Links 39 🎵", "MP3_LINKS_39"),
    Pair("MP3 Links 40 🎵", "MP3_LINKS_40"),
    Pair("MP3 Links 41 🎵", "MP3_LINKS_41"),
    Pair("MP3 Links 42 🎵", "MP3_LINKS_42"),
    Pair("MP3 Links 43 🎵", "MP3_LINKS_43"),
    Pair("MP3 Links 44 🎵", "MP3_LINKS_44"),
    Pair("MP3 Links 45 🎵", "MP3_LINKS_45"),
    Pair("MP3 Links 46 🎵", "MP3_LINKS_46"),
    Pair("MP3 Links 47 🎵", "MP3_LINKS_47"),
    Pair("MP3 Links 48 🎵", "MP3_LINKS_48"),
    Pair("MP3 Links 49 🎵", "MP3_LINKS_49"),
    Pair("MP3 Links 50 🎵", "MP3_LINKS_50"),
    Pair("MP3 Links 51 🎵", "MP3_LINKS_51"),
    Pair("MP3 Links 52 🎵", "MP3_LINKS_52"),
    Pair("MP3 Links 53 🎵", "MP3_LINKS_53"),
    Pair("MP3 Links 54 🎵", "MP3_LINKS_54"),
    Pair("MP3 Links 55 🎵", "MP3_LINKS_55"),
    Pair("MP3 Links 56 🎵", "MP3_LINKS_56"),
    Pair("MP3 Links 57 🎵", "MP3_LINKS_57"),
    Pair("MP3 Links 58 🎵", "MP3_LINKS_58"),
    Pair("MP3 Links 59 🎵", "MP3_LINKS_59"),
    Pair("MP3 Links 60 🎵", "MP3_LINKS_60"),
    Pair("MP3 Links 61 🎵", "MP3_LINKS_61"),
    Pair("MP3 Links 62 🎵", "MP3_LINKS_62"),
    Pair("MP3 Links 63 🎵", "MP3_LINKS_63"),
    Pair("MP3 Links 64 🎵", "MP3_LINKS_64"),
    Pair("MP3 Links 65 🎵", "MP3_LINKS_65"),
    Pair("MP3 Links 66 🎵", "MP3_LINKS_66"),
    Pair("MP3 Links 67 🎵", "MP3_LINKS_67"),
    Pair("MP3 Links 68 🎵", "MP3_LINKS_68"),
    Pair("MP3 Links 69 🎵", "MP3_LINKS_69"),
    Pair("MP3 Links 70 🎵", "MP3_LINKS_70"),
    Pair("MP3 Links 71 🎵", "MP3_LINKS_71"),
    Pair("MP3 Links 72 🎵", "MP3_LINKS_72"),
    Pair("MP3 Links 73 🎵", "MP3_LINKS_73"),
    Pair("MP3 Links 74 🎵", "MP3_LINKS_74"),
    Pair("MP3 Links 75 🎵", "MP3_LINKS_75"),
    Pair("MP3 Links 76 🎵", "MP3_LINKS_76"),
    Pair("MP3 Links 77 🎵", "MP3_LINKS_77"),
    Pair("MP3 Links 78 🎵", "MP3_LINKS_78"),
    Pair("MP3 Links 79 🎵", "MP3_LINKS_79"),
    Pair("MP3 Links 80 🎵", "MP3_LINKS_80"),
    Pair("MP3 Links 81 🎵", "MP3_LINKS_81"),
    Pair("MP3 Links 82 🎵", "MP3_LINKS_82"),
    Pair("MP3 Links 83 🎵", "MP3_LINKS_83"),
    Pair("MP3 Links 84 🎵", "MP3_LINKS_84"),
    Pair("MP3 Links 85 🎵", "MP3_LINKS_85"),
    Pair("MP3 Links 86 🎵", "MP3_LINKS_86"),
    Pair("MP3 Links 87 🎵", "MP3_LINKS_87"),
    Pair("MP3 Links 88 🎵", "MP3_LINKS_88"),
    Pair("MP3 Links 89 🎵", "MP3_LINKS_89"),
    Pair("MP3 Links 90 🎵", "MP3_LINKS_90"),
    Pair("MP3 Links 91 🎵", "MP3_LINKS_91"),
    Pair("MP3 Links 92 🎵", "MP3_LINKS_92"),
    Pair("MP3 Links 93 🎵", "MP3_LINKS_93"),
    Pair("MP3 Links 94 🎵", "MP3_LINKS_94"),
    Pair("MP3 Links 95 🎵", "MP3_LINKS_95"),
    Pair("MP3 Links 96 🎵", "MP3_LINKS_96"),
    Pair("MP3 Links 97 🎵", "MP3_LINKS_97"),
    Pair("MP3 Links 98 🎵", "MP3_LINKS_98"),
    Pair("MP3 Links 99 🎵", "MP3_LINKS_99"),
    Pair("MP3 Links 100 🎵", "MP3_LINKS_100"),
    Pair("MP3 Links 101 🎵", "MP3_LINKS_101"),
    Pair("MP3 Links 102 🎵", "MP3_LINKS_102"),
    Pair("MP3 Links 103 🎵", "MP3_LINKS_103"),
    Pair("MP3 Links 104 🎵", "MP3_LINKS_104"),
    Pair("MP3 Links 105 🎵", "MP3_LINKS_105"),
    Pair("MP3 Links 106 🎵", "MP3_LINKS_106"),
    Pair("MP3 Links 107 🎵", "MP3_LINKS_107"),
    Pair("MP3 Links 108 🎵", "MP3_LINKS_108"),
    Pair("MP3 Links 109 🎵", "MP3_LINKS_109"),
    Pair("MP3 Links 110 🎵", "MP3_LINKS_110"),
    Pair("MP3 Links 111 🎵", "MP3_LINKS_111"),
    Pair("MP3 Links 112 🎵", "MP3_LINKS_112"),
    Pair("MP3 Links 113 🎵", "MP3_LINKS_113"),
    Pair("MP3 Links 114 🎵", "MP3_LINKS_114"),
    Pair("MP3 Links 115 🎵", "MP3_LINKS_115"),
    Pair("MP3 Links 116 🎵", "MP3_LINKS_116"),
    Pair("MP3 Links 117 🎵", "MP3_LINKS_117"),
    Pair("MP3 Links 118 🎵", "MP3_LINKS_118"),
    Pair("MP3 Links 119 🎵", "MP3_LINKS_119"),
    Pair("MP3 Links 120 🎵", "MP3_LINKS_120"),
    Pair("MP3 Links 121 🎵", "MP3_LINKS_121"),
    Pair("MP3 Links 122 🎵", "MP3_LINKS_122"),
    Pair("MP3 Links 123 🎵", "MP3_LINKS_123"),
    Pair("MP3 Links 124 🎵", "MP3_LINKS_124"),
    
    // Countries
    Pair("🇮🇳 India", "IN"),
    Pair("🇮🇪 Ireland", "IE")
)
